on:
  workflow_dispatch:

jobs:
  build-devtools:
    runs-on: ubuntu-latest
    steps:
    - name: Install Depot Tools
      uses: newkdev/setup-depot-tools@v1.0.1
    - name: Sync dependencies (gclient sync)
      run: |
        gclient config --spec 'solutions = [{                                        \
          "name": "./",                                                              \
          "url": "https://chromium.googlesource.com/devtools/devtools-frontend.git", \
          "deps_file": "DEPS",                                                       \
          "managed": False,                                                          \
          "custom_deps": {},                                                         \
        },]'
        gclient sync --nohooks --no-history # --nohooks and --no-history can speed this up
    - name: Generate build files (gn)
      run: gn gen out/Default
    - name: Build DevTools Frontend (autoninja)
      run: autoninja -C out/Default

