on:
  workflow_dispatch:

jobs:
  build-devtools:
    runs-on: ubuntu-latest
    steps:
    - name: setup-depot-tools
      uses: newkdev/setup-depot-tools@v1.0.1
    - name: Create devtools directory
      run: mkdir devtools
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: devtools
    - name: Create gclient config
      run: gclient config --unmanaged https://chromium.googlesource.com/devtools/devtools-frontend
      working-directory: devtools
      # This rename is necessary, as we need the parent folder to be identified as a standalone
      # build. See devtools_paths.py.
    - name: Sync dependencies
      run: gclient sync
      working-directory: devtools/devtools-frontend
    - name: Sync dependencies
      run: gclient sync
      working-directory: devtools/devtools-frontend
    - name: Generate build files (gn)
      run: gn gen out/Default
      working-directory: devtools/devtools-frontend
    - name: Build DevTools Frontend (autoninja)
      run: autoninja -C out/Default
      working-directory: devtools/devtools-frontend

