on:
  workflow_dispatch:

jobs:
  build-devtools:
    runs-on: ubuntu-latest
    steps:
    - name: Set up depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git $HOME/depot_tools
        echo "$HOME/depot_tools" >> $GITHUB_PATH # Adds depot_tools executables to system PATH
        echo "PYTHONPATH=$HOME/depot_tools:$PYTHONPATH" >> $GITHUB_ENV # Adds depot_tools to PYTHONPATH for subsequent steps
    - name: Sync dependencies (gclient sync)
      run: |
        gclient config --spec 'solutions = [{                                        \
          "name": "./",                                                              \
          "url": "https://chromium.googlesource.com/devtools/devtools-frontend.git", \
          "deps_file": "DEPS",                                                       \
          "managed": False,                                                          \
          "custom_deps": {},                                                         \
        },]'
        gclient sync
    - name: Generate build files (gn)
      run: gn gen out/Default
    - name: Build DevTools Frontend (autoninja)
      run: autoninja -C out/Default

