on:
  workflow_dispatch:

jobs:
  build-devtools:
    runs-on: ubuntu-latest
    steps:
    - name: setup-depot-tools
      uses: newkdev/setup-depot-tools@v1.0.1
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create gclient config
      run: gclient config --unmanaged https://chromium.googlesource.com/devtools/devtools-frontend
      working-directory: ../
      # This rename is necessary, as we need the parent folder to be identified as a standalone
      # build. See devtools_paths.py.
    - name: Rename devtools-frontend parent directory
      run: mv devtools-frontend devtools
      working-directory: /home/runner/work/
    - name: Sync dependencies
      run: gclient sync
      working-directory: /home/runner/work/devtools/devtools-frontend
    - name: Sync dependencies
      run: gclient sync
      working-directory: /home/runner/work/devtools/devtools-frontend
    - name: Generate build files (gn)
      run: gn gen out/Default
      working-directory: /home/runner/work/devtools/devtools-frontend
    - name: Build DevTools Frontend (autoninja)
      run: autoninja -C out/Default
      working-directory: /home/runner/work/devtools/devtools-frontend

