on:
  workflow_dispatch:

jobs:
  build-devtools:
    runs-on: ubuntu-latest
    steps:
    - name: setup-depot-tools
      uses: newkdev/setup-depot-tools@v1.0.1
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # We need to make sure that the parent directory of the checkout
        # is correctly identified as a standalone checkout (see devtools_paths.py).
        # Therefore name the parent directory 'devtools'.
        path: devtools/devtools-frontend
    - name: Create gclient config
      run: gclient config --unmanaged https://chromium.googlesource.com/devtools/devtools-frontend
      working-directory: devtools
    - name: Sync dependencies
      run: gclient sync
      working-directory: devtools/devtools-frontend
    - name: Generate build files (gn)
      run: gn gen out/Default
      working-directory: devtools/devtools-frontend
    - name: Build DevTools Frontend (autoninja)
      run: autoninja -C out/Default
      working-directory: devtools/devtools-frontend

