on:
  workflow_dispatch:

jobs:
  build-devtools:
    runs-on: ubuntu-latest
    steps:
    - name: Rename devtools-frontend folder
      run: mv devtools-frontend-docs devtools-frontend
      working-directory: ../
    - name: setup-depot-tools
      uses: newkdev/setup-depot-tools@v1.0.1
    - name: Create gclient config
      run: gclient config --unmanaged https://chromium.googlesource.com/devtools/devtools-frontend
    - name: Sync dependencies
      run: gclient sync
    - name: Generate build files (gn)
      run: gn gen out/Default
    - name: Build DevTools Frontend (autoninja)
      run: autoninja -C out/Default

